# Generated by Django 4.0 on 2022-08-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='email_is_verified',
            field=models.BooleanField(default=False, verbose_name='e-mail подтверждён'),
        ),
    ]
