# Generated by Django 4.0 on 2022-08-14 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, verbose_name='Название подарка')),
                ('status', models.CharField(choices=[('unselect', 'Ещё не выбрано'), ('selected', 'Выбрано'), ('delivered', 'Доставлено')], default='unselect', max_length=99, verbose_name='Состояние подарка')),
            ],
        ),
        migrations.AlterField(
            model_name='letter',
            name='gift',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='letters.gift'),
        ),
    ]
