# Generated by Django 3.2 on 2022-08-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_gift_alter_letter_gift'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='excel/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='gift',
            options={'verbose_name': 'Подарок', 'verbose_name_plural': 'Подарки'},
        ),
    ]
