# Generated by Django 4.0 on 2022-08-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_auto_20220817_1013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelTable',
        ),
    ]
