# Generated by Django 4.0 on 2022-08-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0005_delete_exceltable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='child',
            name='last_name',
        ),
    ]
