# Generated by Django 4.0 on 2022-09-03 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usertools', '0002_baseuser_email_is_verified'),
        ('letters', '0006_rename_first_name_child_name_remove_child_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='favorite_select',
            field=models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='letter',
            name='picked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='letters', to='usertools.baseuser'),
        ),
    ]
