# Generated by Django 4.0 on 2022-09-04 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('letters', '0007_letter_favorite_select_alter_letter_picked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='favorite_select',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
